language: node_js
node_js:
  - "node"
cache:
  directories:
    - $HOME/.npm
    - "node_modules"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
script: 
  - npm run test:ci
