language: node_js
node_js:
  - "node"
deploy:
  skip_cleanup: true
cache:
  directories:
    - $HOME/.npm
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
