name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Run Docker
        run: npm run docker:all
