name: Build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Run Docker
        run: pnpm run docker
      - name: Docker Report
        run: docker image ls
